/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestBodyOfTheDeleteSessionMethod
 */
export interface RequestBodyOfTheDeleteSessionMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheDeleteSessionMethod
     */
    jsonrpc?: RequestBodyOfTheDeleteSessionMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheDeleteSessionMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheDeleteSessionMethod
     */
    method?: RequestBodyOfTheDeleteSessionMethodMethodEnum;
    /**
     * 
     * @type {object}
     * @memberof RequestBodyOfTheDeleteSessionMethod
     */
    params?: object;
}


/**
 * @export
 */
export const RequestBodyOfTheDeleteSessionMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheDeleteSessionMethodJsonrpcEnum = typeof RequestBodyOfTheDeleteSessionMethodJsonrpcEnum[keyof typeof RequestBodyOfTheDeleteSessionMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheDeleteSessionMethodMethodEnum = {
    DeleteSession: 'delete_session'
} as const;
export type RequestBodyOfTheDeleteSessionMethodMethodEnum = typeof RequestBodyOfTheDeleteSessionMethodMethodEnum[keyof typeof RequestBodyOfTheDeleteSessionMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheDeleteSessionMethod interface.
 */
export function instanceOfRequestBodyOfTheDeleteSessionMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheDeleteSessionMethodFromJSON(json: any): RequestBodyOfTheDeleteSessionMethod {
    return RequestBodyOfTheDeleteSessionMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheDeleteSessionMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheDeleteSessionMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : json['params'],
    };
}

export function RequestBodyOfTheDeleteSessionMethodToJSON(value?: RequestBodyOfTheDeleteSessionMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': value.params,
    };
}

