/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcCreateTestCaseListRequest } from './RpcCreateTestCaseListRequest';
import {
    RpcCreateTestCaseListRequestFromJSON,
    RpcCreateTestCaseListRequestFromJSONTyped,
    RpcCreateTestCaseListRequestToJSON,
} from './RpcCreateTestCaseListRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheCreateTestCaseListMethod
 */
export interface RequestBodyOfTheCreateTestCaseListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheCreateTestCaseListMethod
     */
    jsonrpc?: RequestBodyOfTheCreateTestCaseListMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheCreateTestCaseListMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheCreateTestCaseListMethod
     */
    method?: RequestBodyOfTheCreateTestCaseListMethodMethodEnum;
    /**
     * 
     * @type {RpcCreateTestCaseListRequest}
     * @memberof RequestBodyOfTheCreateTestCaseListMethod
     */
    params?: RpcCreateTestCaseListRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheCreateTestCaseListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheCreateTestCaseListMethodJsonrpcEnum = typeof RequestBodyOfTheCreateTestCaseListMethodJsonrpcEnum[keyof typeof RequestBodyOfTheCreateTestCaseListMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheCreateTestCaseListMethodMethodEnum = {
    CreateTestCaseList: 'create_test_case_list'
} as const;
export type RequestBodyOfTheCreateTestCaseListMethodMethodEnum = typeof RequestBodyOfTheCreateTestCaseListMethodMethodEnum[keyof typeof RequestBodyOfTheCreateTestCaseListMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheCreateTestCaseListMethod interface.
 */
export function instanceOfRequestBodyOfTheCreateTestCaseListMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheCreateTestCaseListMethodFromJSON(json: any): RequestBodyOfTheCreateTestCaseListMethod {
    return RequestBodyOfTheCreateTestCaseListMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheCreateTestCaseListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheCreateTestCaseListMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : RpcCreateTestCaseListRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheCreateTestCaseListMethodToJSON(value?: RequestBodyOfTheCreateTestCaseListMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': RpcCreateTestCaseListRequestToJSON(value.params),
    };
}

