/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcGetAccountProblemSnippetListRequest } from './RpcGetAccountProblemSnippetListRequest';
import {
    RpcGetAccountProblemSnippetListRequestFromJSON,
    RpcGetAccountProblemSnippetListRequestFromJSONTyped,
    RpcGetAccountProblemSnippetListRequestToJSON,
} from './RpcGetAccountProblemSnippetListRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetAccountProblemSnippetListMethod
 */
export interface RequestBodyOfTheGetAccountProblemSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetAccountProblemSnippetListMethod
     */
    jsonrpc?: RequestBodyOfTheGetAccountProblemSnippetListMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetAccountProblemSnippetListMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetAccountProblemSnippetListMethod
     */
    method?: RequestBodyOfTheGetAccountProblemSnippetListMethodMethodEnum;
    /**
     * 
     * @type {RpcGetAccountProblemSnippetListRequest}
     * @memberof RequestBodyOfTheGetAccountProblemSnippetListMethod
     */
    params?: RpcGetAccountProblemSnippetListRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetAccountProblemSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetAccountProblemSnippetListMethodJsonrpcEnum = typeof RequestBodyOfTheGetAccountProblemSnippetListMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetAccountProblemSnippetListMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetAccountProblemSnippetListMethodMethodEnum = {
    GetAccountProblemSnippetList: 'get_account_problem_snippet_list'
} as const;
export type RequestBodyOfTheGetAccountProblemSnippetListMethodMethodEnum = typeof RequestBodyOfTheGetAccountProblemSnippetListMethodMethodEnum[keyof typeof RequestBodyOfTheGetAccountProblemSnippetListMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetAccountProblemSnippetListMethod interface.
 */
export function instanceOfRequestBodyOfTheGetAccountProblemSnippetListMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheGetAccountProblemSnippetListMethodFromJSON(json: any): RequestBodyOfTheGetAccountProblemSnippetListMethod {
    return RequestBodyOfTheGetAccountProblemSnippetListMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetAccountProblemSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetAccountProblemSnippetListMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : RpcGetAccountProblemSnippetListRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetAccountProblemSnippetListMethodToJSON(value?: RequestBodyOfTheGetAccountProblemSnippetListMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': RpcGetAccountProblemSnippetListRequestToJSON(value.params),
    };
}

