/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcGetUserRequest } from './RpcGetUserRequest';
import {
    RpcGetUserRequestFromJSON,
    RpcGetUserRequestFromJSONTyped,
    RpcGetUserRequestToJSON,
} from './RpcGetUserRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetUserMethod
 */
export interface RequestBodyOfTheGetUserMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetUserMethod
     */
    jsonrpc?: RequestBodyOfTheGetUserMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetUserMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetUserMethod
     */
    method?: RequestBodyOfTheGetUserMethodMethodEnum;
    /**
     * 
     * @type {RpcGetUserRequest}
     * @memberof RequestBodyOfTheGetUserMethod
     */
    params?: RpcGetUserRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetUserMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetUserMethodJsonrpcEnum = typeof RequestBodyOfTheGetUserMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetUserMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetUserMethodMethodEnum = {
    GetUser: 'get_user'
} as const;
export type RequestBodyOfTheGetUserMethodMethodEnum = typeof RequestBodyOfTheGetUserMethodMethodEnum[keyof typeof RequestBodyOfTheGetUserMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetUserMethod interface.
 */
export function instanceOfRequestBodyOfTheGetUserMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheGetUserMethodFromJSON(json: any): RequestBodyOfTheGetUserMethod {
    return RequestBodyOfTheGetUserMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetUserMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetUserMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : RpcGetUserRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetUserMethodToJSON(value?: RequestBodyOfTheGetUserMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': RpcGetUserRequestToJSON(value.params),
    };
}

