/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcGetSubmissionSnippetListRequest } from './RpcGetSubmissionSnippetListRequest';
import {
    RpcGetSubmissionSnippetListRequestFromJSON,
    RpcGetSubmissionSnippetListRequestFromJSONTyped,
    RpcGetSubmissionSnippetListRequestToJSON,
} from './RpcGetSubmissionSnippetListRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetSubmissionSnippetListMethod
 */
export interface RequestBodyOfTheGetSubmissionSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetSubmissionSnippetListMethod
     */
    jsonrpc?: RequestBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetSubmissionSnippetListMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetSubmissionSnippetListMethod
     */
    method?: RequestBodyOfTheGetSubmissionSnippetListMethodMethodEnum;
    /**
     * 
     * @type {RpcGetSubmissionSnippetListRequest}
     * @memberof RequestBodyOfTheGetSubmissionSnippetListMethod
     */
    params?: RpcGetSubmissionSnippetListRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum = typeof RequestBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetSubmissionSnippetListMethodMethodEnum = {
    GetSubmissionSnippetList: 'get_submission_snippet_list'
} as const;
export type RequestBodyOfTheGetSubmissionSnippetListMethodMethodEnum = typeof RequestBodyOfTheGetSubmissionSnippetListMethodMethodEnum[keyof typeof RequestBodyOfTheGetSubmissionSnippetListMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetSubmissionSnippetListMethod interface.
 */
export function instanceOfRequestBodyOfTheGetSubmissionSnippetListMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheGetSubmissionSnippetListMethodFromJSON(json: any): RequestBodyOfTheGetSubmissionSnippetListMethod {
    return RequestBodyOfTheGetSubmissionSnippetListMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetSubmissionSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetSubmissionSnippetListMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : RpcGetSubmissionSnippetListRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetSubmissionSnippetListMethodToJSON(value?: RequestBodyOfTheGetSubmissionSnippetListMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': RpcGetSubmissionSnippetListRequestToJSON(value.params),
    };
}

