/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestBodyOfTheGetSessionMethod
 */
export interface RequestBodyOfTheGetSessionMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetSessionMethod
     */
    jsonrpc?: RequestBodyOfTheGetSessionMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetSessionMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetSessionMethod
     */
    method?: RequestBodyOfTheGetSessionMethodMethodEnum;
    /**
     * 
     * @type {object}
     * @memberof RequestBodyOfTheGetSessionMethod
     */
    params?: object;
}


/**
 * @export
 */
export const RequestBodyOfTheGetSessionMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetSessionMethodJsonrpcEnum = typeof RequestBodyOfTheGetSessionMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetSessionMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetSessionMethodMethodEnum = {
    GetSession: 'get_session'
} as const;
export type RequestBodyOfTheGetSessionMethodMethodEnum = typeof RequestBodyOfTheGetSessionMethodMethodEnum[keyof typeof RequestBodyOfTheGetSessionMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetSessionMethod interface.
 */
export function instanceOfRequestBodyOfTheGetSessionMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheGetSessionMethodFromJSON(json: any): RequestBodyOfTheGetSessionMethod {
    return RequestBodyOfTheGetSessionMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetSessionMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetSessionMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : json['params'],
    };
}

export function RequestBodyOfTheGetSessionMethodToJSON(value?: RequestBodyOfTheGetSessionMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': value.params,
    };
}

