/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcCreateTestCaseRequest } from './RpcCreateTestCaseRequest';
import {
    RpcCreateTestCaseRequestFromJSON,
    RpcCreateTestCaseRequestFromJSONTyped,
    RpcCreateTestCaseRequestToJSON,
} from './RpcCreateTestCaseRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheCreateTestCaseMethod
 */
export interface RequestBodyOfTheCreateTestCaseMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheCreateTestCaseMethod
     */
    jsonrpc?: RequestBodyOfTheCreateTestCaseMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheCreateTestCaseMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheCreateTestCaseMethod
     */
    method?: RequestBodyOfTheCreateTestCaseMethodMethodEnum;
    /**
     * 
     * @type {RpcCreateTestCaseRequest}
     * @memberof RequestBodyOfTheCreateTestCaseMethod
     */
    params?: RpcCreateTestCaseRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheCreateTestCaseMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheCreateTestCaseMethodJsonrpcEnum = typeof RequestBodyOfTheCreateTestCaseMethodJsonrpcEnum[keyof typeof RequestBodyOfTheCreateTestCaseMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheCreateTestCaseMethodMethodEnum = {
    CreateTestCase: 'create_test_case'
} as const;
export type RequestBodyOfTheCreateTestCaseMethodMethodEnum = typeof RequestBodyOfTheCreateTestCaseMethodMethodEnum[keyof typeof RequestBodyOfTheCreateTestCaseMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheCreateTestCaseMethod interface.
 */
export function instanceOfRequestBodyOfTheCreateTestCaseMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheCreateTestCaseMethodFromJSON(json: any): RequestBodyOfTheCreateTestCaseMethod {
    return RequestBodyOfTheCreateTestCaseMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheCreateTestCaseMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheCreateTestCaseMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : RpcCreateTestCaseRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheCreateTestCaseMethodToJSON(value?: RequestBodyOfTheCreateTestCaseMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': RpcCreateTestCaseRequestToJSON(value.params),
    };
}

