/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcUpdateProblemRequest } from './RpcUpdateProblemRequest';
import {
    RpcUpdateProblemRequestFromJSON,
    RpcUpdateProblemRequestFromJSONTyped,
    RpcUpdateProblemRequestToJSON,
} from './RpcUpdateProblemRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheUpdateProblemMethod
 */
export interface RequestBodyOfTheUpdateProblemMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheUpdateProblemMethod
     */
    jsonrpc?: RequestBodyOfTheUpdateProblemMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheUpdateProblemMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheUpdateProblemMethod
     */
    method?: RequestBodyOfTheUpdateProblemMethodMethodEnum;
    /**
     * 
     * @type {RpcUpdateProblemRequest}
     * @memberof RequestBodyOfTheUpdateProblemMethod
     */
    params?: RpcUpdateProblemRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheUpdateProblemMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheUpdateProblemMethodJsonrpcEnum = typeof RequestBodyOfTheUpdateProblemMethodJsonrpcEnum[keyof typeof RequestBodyOfTheUpdateProblemMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheUpdateProblemMethodMethodEnum = {
    UpdateProblem: 'update_problem'
} as const;
export type RequestBodyOfTheUpdateProblemMethodMethodEnum = typeof RequestBodyOfTheUpdateProblemMethodMethodEnum[keyof typeof RequestBodyOfTheUpdateProblemMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheUpdateProblemMethod interface.
 */
export function instanceOfRequestBodyOfTheUpdateProblemMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheUpdateProblemMethodFromJSON(json: any): RequestBodyOfTheUpdateProblemMethod {
    return RequestBodyOfTheUpdateProblemMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheUpdateProblemMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheUpdateProblemMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : RpcUpdateProblemRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheUpdateProblemMethodToJSON(value?: RequestBodyOfTheUpdateProblemMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': RpcUpdateProblemRequestToJSON(value.params),
    };
}

