/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcGetTestCaseRequest } from './RpcGetTestCaseRequest';
import {
    RpcGetTestCaseRequestFromJSON,
    RpcGetTestCaseRequestFromJSONTyped,
    RpcGetTestCaseRequestToJSON,
} from './RpcGetTestCaseRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetTestCaseMethod
 */
export interface RequestBodyOfTheGetTestCaseMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetTestCaseMethod
     */
    jsonrpc?: RequestBodyOfTheGetTestCaseMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetTestCaseMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetTestCaseMethod
     */
    method?: RequestBodyOfTheGetTestCaseMethodMethodEnum;
    /**
     * 
     * @type {RpcGetTestCaseRequest}
     * @memberof RequestBodyOfTheGetTestCaseMethod
     */
    params?: RpcGetTestCaseRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetTestCaseMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetTestCaseMethodJsonrpcEnum = typeof RequestBodyOfTheGetTestCaseMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetTestCaseMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetTestCaseMethodMethodEnum = {
    GetTestCase: 'get_test_case'
} as const;
export type RequestBodyOfTheGetTestCaseMethodMethodEnum = typeof RequestBodyOfTheGetTestCaseMethodMethodEnum[keyof typeof RequestBodyOfTheGetTestCaseMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetTestCaseMethod interface.
 */
export function instanceOfRequestBodyOfTheGetTestCaseMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheGetTestCaseMethodFromJSON(json: any): RequestBodyOfTheGetTestCaseMethod {
    return RequestBodyOfTheGetTestCaseMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetTestCaseMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetTestCaseMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : RpcGetTestCaseRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetTestCaseMethodToJSON(value?: RequestBodyOfTheGetTestCaseMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': RpcGetTestCaseRequestToJSON(value.params),
    };
}

