/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcEchoRequest } from './RpcEchoRequest';
import {
    RpcEchoRequestFromJSON,
    RpcEchoRequestFromJSONTyped,
    RpcEchoRequestToJSON,
} from './RpcEchoRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheEchoMethod
 */
export interface RequestBodyOfTheEchoMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheEchoMethod
     */
    jsonrpc?: RequestBodyOfTheEchoMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheEchoMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheEchoMethod
     */
    method?: RequestBodyOfTheEchoMethodMethodEnum;
    /**
     * 
     * @type {RpcEchoRequest}
     * @memberof RequestBodyOfTheEchoMethod
     */
    params?: RpcEchoRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheEchoMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheEchoMethodJsonrpcEnum = typeof RequestBodyOfTheEchoMethodJsonrpcEnum[keyof typeof RequestBodyOfTheEchoMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheEchoMethodMethodEnum = {
    Echo: 'echo'
} as const;
export type RequestBodyOfTheEchoMethodMethodEnum = typeof RequestBodyOfTheEchoMethodMethodEnum[keyof typeof RequestBodyOfTheEchoMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheEchoMethod interface.
 */
export function instanceOfRequestBodyOfTheEchoMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheEchoMethodFromJSON(json: any): RequestBodyOfTheEchoMethod {
    return RequestBodyOfTheEchoMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheEchoMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheEchoMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : RpcEchoRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheEchoMethodToJSON(value?: RequestBodyOfTheEchoMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': RpcEchoRequestToJSON(value.params),
    };
}

