/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod
 */
export interface RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod
     */
    jsonrpc?: RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod
     */
    method?: RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodMethodEnum;
    /**
     * 
     * @type {object}
     * @memberof RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod
     */
    params?: object;
}


/**
 * @export
 */
export const RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodJsonrpcEnum = typeof RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodMethodEnum = {
    GetAndUpdateFirstSubmittedSubmissionToExecuting: 'get_and_update_first_submitted_submission_to_executing'
} as const;
export type RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodMethodEnum = typeof RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodMethodEnum[keyof typeof RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod interface.
 */
export function instanceOfRequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodFromJSON(json: any): RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod {
    return RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : json['params'],
    };
}

export function RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodToJSON(value?: RequestBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': value.params,
    };
}

