/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcGetUserProblemSnippetListRequest } from './RpcGetUserProblemSnippetListRequest';
import {
    RpcGetUserProblemSnippetListRequestFromJSON,
    RpcGetUserProblemSnippetListRequestFromJSONTyped,
    RpcGetUserProblemSnippetListRequestToJSON,
} from './RpcGetUserProblemSnippetListRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetUserProblemSnippetListMethod
 */
export interface RequestBodyOfTheGetUserProblemSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetUserProblemSnippetListMethod
     */
    jsonrpc?: RequestBodyOfTheGetUserProblemSnippetListMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetUserProblemSnippetListMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetUserProblemSnippetListMethod
     */
    method?: RequestBodyOfTheGetUserProblemSnippetListMethodMethodEnum;
    /**
     * 
     * @type {RpcGetUserProblemSnippetListRequest}
     * @memberof RequestBodyOfTheGetUserProblemSnippetListMethod
     */
    params?: RpcGetUserProblemSnippetListRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetUserProblemSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetUserProblemSnippetListMethodJsonrpcEnum = typeof RequestBodyOfTheGetUserProblemSnippetListMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetUserProblemSnippetListMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetUserProblemSnippetListMethodMethodEnum = {
    GetUserProblemSnippetList: 'get_user_problem_snippet_list'
} as const;
export type RequestBodyOfTheGetUserProblemSnippetListMethodMethodEnum = typeof RequestBodyOfTheGetUserProblemSnippetListMethodMethodEnum[keyof typeof RequestBodyOfTheGetUserProblemSnippetListMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetUserProblemSnippetListMethod interface.
 */
export function instanceOfRequestBodyOfTheGetUserProblemSnippetListMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheGetUserProblemSnippetListMethodFromJSON(json: any): RequestBodyOfTheGetUserProblemSnippetListMethod {
    return RequestBodyOfTheGetUserProblemSnippetListMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetUserProblemSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetUserProblemSnippetListMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : RpcGetUserProblemSnippetListRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetUserProblemSnippetListMethodToJSON(value?: RequestBodyOfTheGetUserProblemSnippetListMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': RpcGetUserProblemSnippetListRequestToJSON(value.params),
    };
}

