/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcGetProblemRequest } from './RpcGetProblemRequest';
import {
    RpcGetProblemRequestFromJSON,
    RpcGetProblemRequestFromJSONTyped,
    RpcGetProblemRequestToJSON,
} from './RpcGetProblemRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetProblemMethod
 */
export interface RequestBodyOfTheGetProblemMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetProblemMethod
     */
    jsonrpc?: RequestBodyOfTheGetProblemMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetProblemMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetProblemMethod
     */
    method?: RequestBodyOfTheGetProblemMethodMethodEnum;
    /**
     * 
     * @type {RpcGetProblemRequest}
     * @memberof RequestBodyOfTheGetProblemMethod
     */
    params?: RpcGetProblemRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetProblemMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetProblemMethodJsonrpcEnum = typeof RequestBodyOfTheGetProblemMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetProblemMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetProblemMethodMethodEnum = {
    GetProblem: 'get_problem'
} as const;
export type RequestBodyOfTheGetProblemMethodMethodEnum = typeof RequestBodyOfTheGetProblemMethodMethodEnum[keyof typeof RequestBodyOfTheGetProblemMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetProblemMethod interface.
 */
export function instanceOfRequestBodyOfTheGetProblemMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheGetProblemMethodFromJSON(json: any): RequestBodyOfTheGetProblemMethod {
    return RequestBodyOfTheGetProblemMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetProblemMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetProblemMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : RpcGetProblemRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetProblemMethodToJSON(value?: RequestBodyOfTheGetProblemMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': RpcGetProblemRequestToJSON(value.params),
    };
}

