/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcUpdateSubmissionRequest } from './RpcUpdateSubmissionRequest';
import {
    RpcUpdateSubmissionRequestFromJSON,
    RpcUpdateSubmissionRequestFromJSONTyped,
    RpcUpdateSubmissionRequestToJSON,
} from './RpcUpdateSubmissionRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheUpdateSubmissionMethod
 */
export interface RequestBodyOfTheUpdateSubmissionMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheUpdateSubmissionMethod
     */
    jsonrpc?: RequestBodyOfTheUpdateSubmissionMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheUpdateSubmissionMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheUpdateSubmissionMethod
     */
    method?: RequestBodyOfTheUpdateSubmissionMethodMethodEnum;
    /**
     * 
     * @type {RpcUpdateSubmissionRequest}
     * @memberof RequestBodyOfTheUpdateSubmissionMethod
     */
    params?: RpcUpdateSubmissionRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheUpdateSubmissionMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheUpdateSubmissionMethodJsonrpcEnum = typeof RequestBodyOfTheUpdateSubmissionMethodJsonrpcEnum[keyof typeof RequestBodyOfTheUpdateSubmissionMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheUpdateSubmissionMethodMethodEnum = {
    UpdateSubmission: 'update_submission'
} as const;
export type RequestBodyOfTheUpdateSubmissionMethodMethodEnum = typeof RequestBodyOfTheUpdateSubmissionMethodMethodEnum[keyof typeof RequestBodyOfTheUpdateSubmissionMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheUpdateSubmissionMethod interface.
 */
export function instanceOfRequestBodyOfTheUpdateSubmissionMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheUpdateSubmissionMethodFromJSON(json: any): RequestBodyOfTheUpdateSubmissionMethod {
    return RequestBodyOfTheUpdateSubmissionMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheUpdateSubmissionMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheUpdateSubmissionMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : RpcUpdateSubmissionRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheUpdateSubmissionMethodToJSON(value?: RequestBodyOfTheUpdateSubmissionMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': RpcUpdateSubmissionRequestToJSON(value.params),
    };
}

