/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcGetAccountRequest } from './RpcGetAccountRequest';
import {
    RpcGetAccountRequestFromJSON,
    RpcGetAccountRequestFromJSONTyped,
    RpcGetAccountRequestToJSON,
} from './RpcGetAccountRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetAccountMethod
 */
export interface RequestBodyOfTheGetAccountMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetAccountMethod
     */
    jsonrpc?: RequestBodyOfTheGetAccountMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetAccountMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetAccountMethod
     */
    method?: RequestBodyOfTheGetAccountMethodMethodEnum;
    /**
     * 
     * @type {RpcGetAccountRequest}
     * @memberof RequestBodyOfTheGetAccountMethod
     */
    params?: RpcGetAccountRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetAccountMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetAccountMethodJsonrpcEnum = typeof RequestBodyOfTheGetAccountMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetAccountMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetAccountMethodMethodEnum = {
    GetAccount: 'get_account'
} as const;
export type RequestBodyOfTheGetAccountMethodMethodEnum = typeof RequestBodyOfTheGetAccountMethodMethodEnum[keyof typeof RequestBodyOfTheGetAccountMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetAccountMethod interface.
 */
export function instanceOfRequestBodyOfTheGetAccountMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBodyOfTheGetAccountMethodFromJSON(json: any): RequestBodyOfTheGetAccountMethod {
    return RequestBodyOfTheGetAccountMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetAccountMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetAccountMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'method': !exists(json, 'method') ? undefined : json['method'],
        'params': !exists(json, 'params') ? undefined : RpcGetAccountRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetAccountMethodToJSON(value?: RequestBodyOfTheGetAccountMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'method': value.method,
        'params': RpcGetAccountRequestToJSON(value.params),
    };
}

