/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcGetAccountResponse } from './RpcGetAccountResponse';
import {
    RpcGetAccountResponseFromJSON,
    RpcGetAccountResponseFromJSONTyped,
    RpcGetAccountResponseToJSON,
} from './RpcGetAccountResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetAccountMethod
 */
export interface ResponseBodyOfTheGetAccountMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetAccountMethod
     */
    jsonrpc?: ResponseBodyOfTheGetAccountMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetAccountMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetAccountMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetAccountResponse}
     * @memberof ResponseBodyOfTheGetAccountMethod
     */
    result?: RpcGetAccountResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetAccountMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetAccountMethodJsonrpcEnum = typeof ResponseBodyOfTheGetAccountMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetAccountMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetAccountMethod interface.
 */
export function instanceOfResponseBodyOfTheGetAccountMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheGetAccountMethodFromJSON(json: any): ResponseBodyOfTheGetAccountMethod {
    return ResponseBodyOfTheGetAccountMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetAccountMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetAccountMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcGetAccountResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetAccountMethodToJSON(value?: ResponseBodyOfTheGetAccountMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcGetAccountResponseToJSON(value.result),
    };
}

