/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcCreateProblemResponse } from './RpcCreateProblemResponse';
import {
    RpcCreateProblemResponseFromJSON,
    RpcCreateProblemResponseFromJSONTyped,
    RpcCreateProblemResponseToJSON,
} from './RpcCreateProblemResponse';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheCreateProblemMethod
 */
export interface ResponseBodyOfTheCreateProblemMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheCreateProblemMethod
     */
    jsonrpc?: ResponseBodyOfTheCreateProblemMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheCreateProblemMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheCreateProblemMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcCreateProblemResponse}
     * @memberof ResponseBodyOfTheCreateProblemMethod
     */
    result?: RpcCreateProblemResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheCreateProblemMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheCreateProblemMethodJsonrpcEnum = typeof ResponseBodyOfTheCreateProblemMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheCreateProblemMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheCreateProblemMethod interface.
 */
export function instanceOfResponseBodyOfTheCreateProblemMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheCreateProblemMethodFromJSON(json: any): ResponseBodyOfTheCreateProblemMethod {
    return ResponseBodyOfTheCreateProblemMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheCreateProblemMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheCreateProblemMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcCreateProblemResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheCreateProblemMethodToJSON(value?: ResponseBodyOfTheCreateProblemMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcCreateProblemResponseToJSON(value.result),
    };
}

