/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcGetAccountProblemSubmissionSnippetListResponse } from './RpcGetAccountProblemSubmissionSnippetListResponse';
import {
    RpcGetAccountProblemSubmissionSnippetListResponseFromJSON,
    RpcGetAccountProblemSubmissionSnippetListResponseFromJSONTyped,
    RpcGetAccountProblemSubmissionSnippetListResponseToJSON,
} from './RpcGetAccountProblemSubmissionSnippetListResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethod
 */
export interface ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethod
     */
    jsonrpc?: ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetAccountProblemSubmissionSnippetListResponse}
     * @memberof ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethod
     */
    result?: RpcGetAccountProblemSubmissionSnippetListResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethodJsonrpcEnum = typeof ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethod interface.
 */
export function instanceOfResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethodFromJSON(json: any): ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethod {
    return ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcGetAccountProblemSubmissionSnippetListResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethodToJSON(value?: ResponseBodyOfTheGetAccountProblemSubmissionSnippetListMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcGetAccountProblemSubmissionSnippetListResponseToJSON(value.result),
    };
}

