/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcGetProblemResponse } from './RpcGetProblemResponse';
import {
    RpcGetProblemResponseFromJSON,
    RpcGetProblemResponseFromJSONTyped,
    RpcGetProblemResponseToJSON,
} from './RpcGetProblemResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetProblemMethod
 */
export interface ResponseBodyOfTheGetProblemMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetProblemMethod
     */
    jsonrpc?: ResponseBodyOfTheGetProblemMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetProblemMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetProblemMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetProblemResponse}
     * @memberof ResponseBodyOfTheGetProblemMethod
     */
    result?: RpcGetProblemResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetProblemMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetProblemMethodJsonrpcEnum = typeof ResponseBodyOfTheGetProblemMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetProblemMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetProblemMethod interface.
 */
export function instanceOfResponseBodyOfTheGetProblemMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheGetProblemMethodFromJSON(json: any): ResponseBodyOfTheGetProblemMethod {
    return ResponseBodyOfTheGetProblemMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetProblemMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetProblemMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcGetProblemResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetProblemMethodToJSON(value?: ResponseBodyOfTheGetProblemMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcGetProblemResponseToJSON(value.result),
    };
}

