/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheDeleteSubmissionMethod
 */
export interface ResponseBodyOfTheDeleteSubmissionMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheDeleteSubmissionMethod
     */
    jsonrpc?: ResponseBodyOfTheDeleteSubmissionMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheDeleteSubmissionMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheDeleteSubmissionMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {object}
     * @memberof ResponseBodyOfTheDeleteSubmissionMethod
     */
    result?: object;
}


/**
 * @export
 */
export const ResponseBodyOfTheDeleteSubmissionMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheDeleteSubmissionMethodJsonrpcEnum = typeof ResponseBodyOfTheDeleteSubmissionMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheDeleteSubmissionMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheDeleteSubmissionMethod interface.
 */
export function instanceOfResponseBodyOfTheDeleteSubmissionMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheDeleteSubmissionMethodFromJSON(json: any): ResponseBodyOfTheDeleteSubmissionMethod {
    return ResponseBodyOfTheDeleteSubmissionMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheDeleteSubmissionMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheDeleteSubmissionMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : json['result'],
    };
}

export function ResponseBodyOfTheDeleteSubmissionMethodToJSON(value?: ResponseBodyOfTheDeleteSubmissionMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': value.result,
    };
}

