/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcEchoResponse } from './RpcEchoResponse';
import {
    RpcEchoResponseFromJSON,
    RpcEchoResponseFromJSONTyped,
    RpcEchoResponseToJSON,
} from './RpcEchoResponse';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheEchoMethod
 */
export interface ResponseBodyOfTheEchoMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheEchoMethod
     */
    jsonrpc?: ResponseBodyOfTheEchoMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheEchoMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheEchoMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcEchoResponse}
     * @memberof ResponseBodyOfTheEchoMethod
     */
    result?: RpcEchoResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheEchoMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheEchoMethodJsonrpcEnum = typeof ResponseBodyOfTheEchoMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheEchoMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheEchoMethod interface.
 */
export function instanceOfResponseBodyOfTheEchoMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheEchoMethodFromJSON(json: any): ResponseBodyOfTheEchoMethod {
    return ResponseBodyOfTheEchoMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheEchoMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheEchoMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcEchoResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheEchoMethodToJSON(value?: ResponseBodyOfTheEchoMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcEchoResponseToJSON(value.result),
    };
}

