/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcGetUserListResponse } from './RpcGetUserListResponse';
import {
    RpcGetUserListResponseFromJSON,
    RpcGetUserListResponseFromJSONTyped,
    RpcGetUserListResponseToJSON,
} from './RpcGetUserListResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetUserListMethod
 */
export interface ResponseBodyOfTheGetUserListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetUserListMethod
     */
    jsonrpc?: ResponseBodyOfTheGetUserListMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetUserListMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetUserListMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetUserListResponse}
     * @memberof ResponseBodyOfTheGetUserListMethod
     */
    result?: RpcGetUserListResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetUserListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetUserListMethodJsonrpcEnum = typeof ResponseBodyOfTheGetUserListMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetUserListMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetUserListMethod interface.
 */
export function instanceOfResponseBodyOfTheGetUserListMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheGetUserListMethodFromJSON(json: any): ResponseBodyOfTheGetUserListMethod {
    return ResponseBodyOfTheGetUserListMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetUserListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetUserListMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcGetUserListResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetUserListMethodToJSON(value?: ResponseBodyOfTheGetUserListMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcGetUserListResponseToJSON(value.result),
    };
}

