/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcUpdateAccountResponse } from './RpcUpdateAccountResponse';
import {
    RpcUpdateAccountResponseFromJSON,
    RpcUpdateAccountResponseFromJSONTyped,
    RpcUpdateAccountResponseToJSON,
} from './RpcUpdateAccountResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheUpdateAccountMethod
 */
export interface ResponseBodyOfTheUpdateAccountMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheUpdateAccountMethod
     */
    jsonrpc?: ResponseBodyOfTheUpdateAccountMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheUpdateAccountMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheUpdateAccountMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcUpdateAccountResponse}
     * @memberof ResponseBodyOfTheUpdateAccountMethod
     */
    result?: RpcUpdateAccountResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheUpdateAccountMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheUpdateAccountMethodJsonrpcEnum = typeof ResponseBodyOfTheUpdateAccountMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheUpdateAccountMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheUpdateAccountMethod interface.
 */
export function instanceOfResponseBodyOfTheUpdateAccountMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheUpdateAccountMethodFromJSON(json: any): ResponseBodyOfTheUpdateAccountMethod {
    return ResponseBodyOfTheUpdateAccountMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheUpdateAccountMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheUpdateAccountMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcUpdateAccountResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheUpdateAccountMethodToJSON(value?: ResponseBodyOfTheUpdateAccountMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcUpdateAccountResponseToJSON(value.result),
    };
}

