/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcGetAndUpdateFirstSubmittedSubmissionAsExecutingResponse } from './RpcGetAndUpdateFirstSubmittedSubmissionAsExecutingResponse';
import {
    RpcGetAndUpdateFirstSubmittedSubmissionAsExecutingResponseFromJSON,
    RpcGetAndUpdateFirstSubmittedSubmissionAsExecutingResponseFromJSONTyped,
    RpcGetAndUpdateFirstSubmittedSubmissionAsExecutingResponseToJSON,
} from './RpcGetAndUpdateFirstSubmittedSubmissionAsExecutingResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethod
 */
export interface ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethod
     */
    jsonrpc?: ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetAndUpdateFirstSubmittedSubmissionAsExecutingResponse}
     * @memberof ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethod
     */
    result?: RpcGetAndUpdateFirstSubmittedSubmissionAsExecutingResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethodJsonrpcEnum = typeof ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethod interface.
 */
export function instanceOfResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethodFromJSON(json: any): ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethod {
    return ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcGetAndUpdateFirstSubmittedSubmissionAsExecutingResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethodToJSON(value?: ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionAsExecutingMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcGetAndUpdateFirstSubmittedSubmissionAsExecutingResponseToJSON(value.result),
    };
}

