/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponse } from './RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponse';
import {
    RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseFromJSON,
    RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseFromJSONTyped,
    RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseToJSON,
} from './RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod
 */
export interface ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod
     */
    jsonrpc?: ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponse}
     * @memberof ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod
     */
    result?: RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodJsonrpcEnum = typeof ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod interface.
 */
export function instanceOfResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodFromJSON(json: any): ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod {
    return ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethodToJSON(value?: ResponseBodyOfTheGetAndUpdateFirstSubmittedSubmissionToExecutingMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseToJSON(value.result),
    };
}

