/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcGetUserSubmissionSnippetListResponse } from './RpcGetUserSubmissionSnippetListResponse';
import {
    RpcGetUserSubmissionSnippetListResponseFromJSON,
    RpcGetUserSubmissionSnippetListResponseFromJSONTyped,
    RpcGetUserSubmissionSnippetListResponseToJSON,
} from './RpcGetUserSubmissionSnippetListResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetUserSubmissionSnippetListMethod
 */
export interface ResponseBodyOfTheGetUserSubmissionSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetUserSubmissionSnippetListMethod
     */
    jsonrpc?: ResponseBodyOfTheGetUserSubmissionSnippetListMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetUserSubmissionSnippetListMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetUserSubmissionSnippetListMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetUserSubmissionSnippetListResponse}
     * @memberof ResponseBodyOfTheGetUserSubmissionSnippetListMethod
     */
    result?: RpcGetUserSubmissionSnippetListResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetUserSubmissionSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetUserSubmissionSnippetListMethodJsonrpcEnum = typeof ResponseBodyOfTheGetUserSubmissionSnippetListMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetUserSubmissionSnippetListMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetUserSubmissionSnippetListMethod interface.
 */
export function instanceOfResponseBodyOfTheGetUserSubmissionSnippetListMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheGetUserSubmissionSnippetListMethodFromJSON(json: any): ResponseBodyOfTheGetUserSubmissionSnippetListMethod {
    return ResponseBodyOfTheGetUserSubmissionSnippetListMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetUserSubmissionSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetUserSubmissionSnippetListMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcGetUserSubmissionSnippetListResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetUserSubmissionSnippetListMethodToJSON(value?: ResponseBodyOfTheGetUserSubmissionSnippetListMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcGetUserSubmissionSnippetListResponseToJSON(value.result),
    };
}

