/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcGetProblemSubmissionSnippetListResponse } from './RpcGetProblemSubmissionSnippetListResponse';
import {
    RpcGetProblemSubmissionSnippetListResponseFromJSON,
    RpcGetProblemSubmissionSnippetListResponseFromJSONTyped,
    RpcGetProblemSubmissionSnippetListResponseToJSON,
} from './RpcGetProblemSubmissionSnippetListResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetProblemSubmissionSnippetListMethod
 */
export interface ResponseBodyOfTheGetProblemSubmissionSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetProblemSubmissionSnippetListMethod
     */
    jsonrpc?: ResponseBodyOfTheGetProblemSubmissionSnippetListMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetProblemSubmissionSnippetListMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetProblemSubmissionSnippetListMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetProblemSubmissionSnippetListResponse}
     * @memberof ResponseBodyOfTheGetProblemSubmissionSnippetListMethod
     */
    result?: RpcGetProblemSubmissionSnippetListResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetProblemSubmissionSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetProblemSubmissionSnippetListMethodJsonrpcEnum = typeof ResponseBodyOfTheGetProblemSubmissionSnippetListMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetProblemSubmissionSnippetListMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetProblemSubmissionSnippetListMethod interface.
 */
export function instanceOfResponseBodyOfTheGetProblemSubmissionSnippetListMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheGetProblemSubmissionSnippetListMethodFromJSON(json: any): ResponseBodyOfTheGetProblemSubmissionSnippetListMethod {
    return ResponseBodyOfTheGetProblemSubmissionSnippetListMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetProblemSubmissionSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetProblemSubmissionSnippetListMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcGetProblemSubmissionSnippetListResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetProblemSubmissionSnippetListMethodToJSON(value?: ResponseBodyOfTheGetProblemSubmissionSnippetListMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcGetProblemSubmissionSnippetListResponseToJSON(value.result),
    };
}

