/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcGetTestCaseResponse } from './RpcGetTestCaseResponse';
import {
    RpcGetTestCaseResponseFromJSON,
    RpcGetTestCaseResponseFromJSONTyped,
    RpcGetTestCaseResponseToJSON,
} from './RpcGetTestCaseResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetTestCaseMethod
 */
export interface ResponseBodyOfTheGetTestCaseMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetTestCaseMethod
     */
    jsonrpc?: ResponseBodyOfTheGetTestCaseMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetTestCaseMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetTestCaseMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetTestCaseResponse}
     * @memberof ResponseBodyOfTheGetTestCaseMethod
     */
    result?: RpcGetTestCaseResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetTestCaseMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetTestCaseMethodJsonrpcEnum = typeof ResponseBodyOfTheGetTestCaseMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetTestCaseMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetTestCaseMethod interface.
 */
export function instanceOfResponseBodyOfTheGetTestCaseMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheGetTestCaseMethodFromJSON(json: any): ResponseBodyOfTheGetTestCaseMethod {
    return ResponseBodyOfTheGetTestCaseMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetTestCaseMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetTestCaseMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcGetTestCaseResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetTestCaseMethodToJSON(value?: ResponseBodyOfTheGetTestCaseMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcGetTestCaseResponseToJSON(value.result),
    };
}

