/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcGetSubmissionSnippetListResponse } from './RpcGetSubmissionSnippetListResponse';
import {
    RpcGetSubmissionSnippetListResponseFromJSON,
    RpcGetSubmissionSnippetListResponseFromJSONTyped,
    RpcGetSubmissionSnippetListResponseToJSON,
} from './RpcGetSubmissionSnippetListResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetSubmissionSnippetListMethod
 */
export interface ResponseBodyOfTheGetSubmissionSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetSubmissionSnippetListMethod
     */
    jsonrpc?: ResponseBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetSubmissionSnippetListMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetSubmissionSnippetListMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetSubmissionSnippetListResponse}
     * @memberof ResponseBodyOfTheGetSubmissionSnippetListMethod
     */
    result?: RpcGetSubmissionSnippetListResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum = typeof ResponseBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetSubmissionSnippetListMethod interface.
 */
export function instanceOfResponseBodyOfTheGetSubmissionSnippetListMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheGetSubmissionSnippetListMethodFromJSON(json: any): ResponseBodyOfTheGetSubmissionSnippetListMethod {
    return ResponseBodyOfTheGetSubmissionSnippetListMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetSubmissionSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetSubmissionSnippetListMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcGetSubmissionSnippetListResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetSubmissionSnippetListMethodToJSON(value?: ResponseBodyOfTheGetSubmissionSnippetListMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcGetSubmissionSnippetListResponseToJSON(value.result),
    };
}

