/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheDeleteTestCaseMethod
 */
export interface ResponseBodyOfTheDeleteTestCaseMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheDeleteTestCaseMethod
     */
    jsonrpc?: ResponseBodyOfTheDeleteTestCaseMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheDeleteTestCaseMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheDeleteTestCaseMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {object}
     * @memberof ResponseBodyOfTheDeleteTestCaseMethod
     */
    result?: object;
}


/**
 * @export
 */
export const ResponseBodyOfTheDeleteTestCaseMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheDeleteTestCaseMethodJsonrpcEnum = typeof ResponseBodyOfTheDeleteTestCaseMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheDeleteTestCaseMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheDeleteTestCaseMethod interface.
 */
export function instanceOfResponseBodyOfTheDeleteTestCaseMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheDeleteTestCaseMethodFromJSON(json: any): ResponseBodyOfTheDeleteTestCaseMethod {
    return ResponseBodyOfTheDeleteTestCaseMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheDeleteTestCaseMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheDeleteTestCaseMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : json['result'],
    };
}

export function ResponseBodyOfTheDeleteTestCaseMethodToJSON(value?: ResponseBodyOfTheDeleteTestCaseMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': value.result,
    };
}

