/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcGetUserProblemSnippetListResponse } from './RpcGetUserProblemSnippetListResponse';
import {
    RpcGetUserProblemSnippetListResponseFromJSON,
    RpcGetUserProblemSnippetListResponseFromJSONTyped,
    RpcGetUserProblemSnippetListResponseToJSON,
} from './RpcGetUserProblemSnippetListResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetUserProblemSnippetListMethod
 */
export interface ResponseBodyOfTheGetUserProblemSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetUserProblemSnippetListMethod
     */
    jsonrpc?: ResponseBodyOfTheGetUserProblemSnippetListMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetUserProblemSnippetListMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetUserProblemSnippetListMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetUserProblemSnippetListResponse}
     * @memberof ResponseBodyOfTheGetUserProblemSnippetListMethod
     */
    result?: RpcGetUserProblemSnippetListResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetUserProblemSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetUserProblemSnippetListMethodJsonrpcEnum = typeof ResponseBodyOfTheGetUserProblemSnippetListMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetUserProblemSnippetListMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetUserProblemSnippetListMethod interface.
 */
export function instanceOfResponseBodyOfTheGetUserProblemSnippetListMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheGetUserProblemSnippetListMethodFromJSON(json: any): ResponseBodyOfTheGetUserProblemSnippetListMethod {
    return ResponseBodyOfTheGetUserProblemSnippetListMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetUserProblemSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetUserProblemSnippetListMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcGetUserProblemSnippetListResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetUserProblemSnippetListMethodToJSON(value?: ResponseBodyOfTheGetUserProblemSnippetListMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcGetUserProblemSnippetListResponseToJSON(value.result),
    };
}

