/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcUpdateTestCaseResponse } from './RpcUpdateTestCaseResponse';
import {
    RpcUpdateTestCaseResponseFromJSON,
    RpcUpdateTestCaseResponseFromJSONTyped,
    RpcUpdateTestCaseResponseToJSON,
} from './RpcUpdateTestCaseResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheUpdateTestCaseMethod
 */
export interface ResponseBodyOfTheUpdateTestCaseMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheUpdateTestCaseMethod
     */
    jsonrpc?: ResponseBodyOfTheUpdateTestCaseMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheUpdateTestCaseMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheUpdateTestCaseMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcUpdateTestCaseResponse}
     * @memberof ResponseBodyOfTheUpdateTestCaseMethod
     */
    result?: RpcUpdateTestCaseResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheUpdateTestCaseMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheUpdateTestCaseMethodJsonrpcEnum = typeof ResponseBodyOfTheUpdateTestCaseMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheUpdateTestCaseMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheUpdateTestCaseMethod interface.
 */
export function instanceOfResponseBodyOfTheUpdateTestCaseMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheUpdateTestCaseMethodFromJSON(json: any): ResponseBodyOfTheUpdateTestCaseMethod {
    return ResponseBodyOfTheUpdateTestCaseMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheUpdateTestCaseMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheUpdateTestCaseMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcUpdateTestCaseResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheUpdateTestCaseMethodToJSON(value?: ResponseBodyOfTheUpdateTestCaseMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcUpdateTestCaseResponseToJSON(value.result),
    };
}

