/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcGetSessionResponse } from './RpcGetSessionResponse';
import {
    RpcGetSessionResponseFromJSON,
    RpcGetSessionResponseFromJSONTyped,
    RpcGetSessionResponseToJSON,
} from './RpcGetSessionResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetSessionMethod
 */
export interface ResponseBodyOfTheGetSessionMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetSessionMethod
     */
    jsonrpc?: ResponseBodyOfTheGetSessionMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetSessionMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetSessionMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetSessionResponse}
     * @memberof ResponseBodyOfTheGetSessionMethod
     */
    result?: RpcGetSessionResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetSessionMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetSessionMethodJsonrpcEnum = typeof ResponseBodyOfTheGetSessionMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetSessionMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetSessionMethod interface.
 */
export function instanceOfResponseBodyOfTheGetSessionMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheGetSessionMethodFromJSON(json: any): ResponseBodyOfTheGetSessionMethod {
    return ResponseBodyOfTheGetSessionMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetSessionMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetSessionMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcGetSessionResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetSessionMethodToJSON(value?: ResponseBodyOfTheGetSessionMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcGetSessionResponseToJSON(value.result),
    };
}

