/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
} from './RpcError';
import type { RpcGetAccountListResponse } from './RpcGetAccountListResponse';
import {
    RpcGetAccountListResponseFromJSON,
    RpcGetAccountListResponseFromJSONTyped,
    RpcGetAccountListResponseToJSON,
} from './RpcGetAccountListResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetAccountListMethod
 */
export interface ResponseBodyOfTheGetAccountListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetAccountListMethod
     */
    jsonrpc?: ResponseBodyOfTheGetAccountListMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetAccountListMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetAccountListMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetAccountListResponse}
     * @memberof ResponseBodyOfTheGetAccountListMethod
     */
    result?: RpcGetAccountListResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetAccountListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetAccountListMethodJsonrpcEnum = typeof ResponseBodyOfTheGetAccountListMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetAccountListMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetAccountListMethod interface.
 */
export function instanceOfResponseBodyOfTheGetAccountListMethod(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseBodyOfTheGetAccountListMethodFromJSON(json: any): ResponseBodyOfTheGetAccountListMethod {
    return ResponseBodyOfTheGetAccountListMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetAccountListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetAccountListMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jsonrpc': !exists(json, 'jsonrpc') ? undefined : json['jsonrpc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'error': !exists(json, 'error') ? undefined : RpcErrorFromJSON(json['error']),
        'result': !exists(json, 'result') ? undefined : RpcGetAccountListResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetAccountListMethodToJSON(value?: ResponseBodyOfTheGetAccountListMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jsonrpc': value.jsonrpc,
        'id': value.id,
        'error': RpcErrorToJSON(value.error),
        'result': RpcGetAccountListResponseToJSON(value.result),
    };
}

