/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RpcAccountRole } from './RpcAccountRole';
import {
    instanceOfRpcAccountRole,
    RpcAccountRoleFromJSON,
    RpcAccountRoleFromJSONTyped,
    RpcAccountRoleToJSON,
} from './RpcAccountRole';

/**
 * @type RpcAccountRole
 * 
 * @export
 */
export type RpcAccountRole = RpcAccountRole;

export function RpcAccountRoleFromJSON(json: any): RpcAccountRole {
    return RpcAccountRoleFromJSONTyped(json, false);
}

export function RpcAccountRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcAccountRole {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...RpcAccountRoleFromJSONTyped(json, true) };
}

export function RpcAccountRoleToJSON(value?: RpcAccountRole | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfRpcAccountRole(value)) {
        return RpcAccountRoleToJSON(value as RpcAccountRole);
    }

    return {};
}

