/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcAccount
 */
export interface RpcAccount {
    /**
     * 
     * @type {number}
     * @memberof RpcAccount
     */
    iD: number;
    /**
     * 
     * @type {string}
     * @memberof RpcAccount
     */
    accountName: string;
    /**
     * 
     * @type {string}
     * @memberof RpcAccount
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof RpcAccount
     */
    role: string;
}

/**
 * Check if a given object implements the RpcAccount interface.
 */
export function instanceOfRpcAccount(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "iD" in value;
    isInstance = isInstance && "accountName" in value;
    isInstance = isInstance && "displayName" in value;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function RpcAccountFromJSON(json: any): RpcAccount {
    return RpcAccountFromJSONTyped(json, false);
}

export function RpcAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'accountName': json['AccountName'],
        'displayName': json['DisplayName'],
        'role': json['Role'],
    };
}

export function RpcAccountToJSON(value?: RpcAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ID': value.iD,
        'AccountName': value.accountName,
        'DisplayName': value.displayName,
        'Role': value.role,
    };
}

