/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RpcUser } from './RpcUser';
import {
    instanceOfRpcUser,
    RpcUserFromJSON,
    RpcUserFromJSONTyped,
    RpcUserToJSON,
} from './RpcUser';

/**
 * @type RpcCreateProblemResponseAuthor
 * 
 * @export
 */
export type RpcCreateProblemResponseAuthor = RpcUser;

export function RpcCreateProblemResponseAuthorFromJSON(json: any): RpcCreateProblemResponseAuthor {
    return RpcCreateProblemResponseAuthorFromJSONTyped(json, false);
}

export function RpcCreateProblemResponseAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateProblemResponseAuthor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...RpcUserFromJSONTyped(json, true) };
}

export function RpcCreateProblemResponseAuthorToJSON(value?: RpcCreateProblemResponseAuthor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfRpcUser(value)) {
        return RpcUserToJSON(value as RpcUser);
    }

    return {};
}

