/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcCreateProblemResponseProblem } from './RpcCreateProblemResponseProblem';
import {
    RpcCreateProblemResponseProblemFromJSON,
    RpcCreateProblemResponseProblemFromJSONTyped,
    RpcCreateProblemResponseProblemToJSON,
} from './RpcCreateProblemResponseProblem';

/**
 * 
 * @export
 * @interface RpcCreateSubmissionResponse
 */
export interface RpcCreateSubmissionResponse {
    /**
     * 
     * @type {RpcCreateProblemResponseProblem}
     * @memberof RpcCreateSubmissionResponse
     */
    problem: RpcCreateProblemResponseProblem;
}

/**
 * Check if a given object implements the RpcCreateSubmissionResponse interface.
 */
export function instanceOfRpcCreateSubmissionResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "problem" in value;

    return isInstance;
}

export function RpcCreateSubmissionResponseFromJSON(json: any): RpcCreateSubmissionResponse {
    return RpcCreateSubmissionResponseFromJSONTyped(json, false);
}

export function RpcCreateSubmissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateSubmissionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'problem': RpcCreateProblemResponseProblemFromJSON(json['Problem']),
    };
}

export function RpcCreateSubmissionResponseToJSON(value?: RpcCreateSubmissionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Problem': RpcCreateProblemResponseProblemToJSON(value.problem),
    };
}

