/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RpcTestCaseSnippet } from './RpcTestCaseSnippet';
import {
    instanceOfRpcTestCaseSnippet,
    RpcTestCaseSnippetFromJSON,
    RpcTestCaseSnippetFromJSONTyped,
    RpcTestCaseSnippetToJSON,
} from './RpcTestCaseSnippet';

/**
 * @type RpcCreateTestCaseResponseTestCaseSnippet
 * 
 * @export
 */
export type RpcCreateTestCaseResponseTestCaseSnippet = RpcTestCaseSnippet;

export function RpcCreateTestCaseResponseTestCaseSnippetFromJSON(json: any): RpcCreateTestCaseResponseTestCaseSnippet {
    return RpcCreateTestCaseResponseTestCaseSnippetFromJSONTyped(json, false);
}

export function RpcCreateTestCaseResponseTestCaseSnippetFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateTestCaseResponseTestCaseSnippet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...RpcTestCaseSnippetFromJSONTyped(json, true) };
}

export function RpcCreateTestCaseResponseTestCaseSnippetToJSON(value?: RpcCreateTestCaseResponseTestCaseSnippet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfRpcTestCaseSnippet(value)) {
        return RpcTestCaseSnippetToJSON(value as RpcTestCaseSnippet);
    }

    return {};
}

