/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcCreateSessionRequest
 */
export interface RpcCreateSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof RpcCreateSessionRequest
     */
    accountName: string;
    /**
     * 
     * @type {string}
     * @memberof RpcCreateSessionRequest
     */
    password: string;
}

/**
 * Check if a given object implements the RpcCreateSessionRequest interface.
 */
export function instanceOfRpcCreateSessionRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountName" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function RpcCreateSessionRequestFromJSON(json: any): RpcCreateSessionRequest {
    return RpcCreateSessionRequestFromJSONTyped(json, false);
}

export function RpcCreateSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateSessionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountName': json['AccountName'],
        'password': json['Password'],
    };
}

export function RpcCreateSessionRequestToJSON(value?: RpcCreateSessionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AccountName': value.accountName,
        'Password': value.password,
    };
}

