/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RpcUserRole } from './RpcUserRole';
import {
    instanceOfRpcUserRole,
    RpcUserRoleFromJSON,
    RpcUserRoleFromJSONTyped,
    RpcUserRoleToJSON,
} from './RpcUserRole';

/**
 * @type RpcCreateUserRequestRole
 * 
 * @export
 */
export type RpcCreateUserRequestRole = RpcUserRole;

export function RpcCreateUserRequestRoleFromJSON(json: any): RpcCreateUserRequestRole {
    return RpcCreateUserRequestRoleFromJSONTyped(json, false);
}

export function RpcCreateUserRequestRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateUserRequestRole {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...RpcUserRoleFromJSONTyped(json, true) };
}

export function RpcCreateUserRequestRoleToJSON(value?: RpcCreateUserRequestRole | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfRpcUserRole(value)) {
        return RpcUserRoleToJSON(value as RpcUserRole);
    }

    return {};
}

