/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RpcAccount } from './RpcAccount';
import {
    instanceOfRpcAccount,
    RpcAccountFromJSON,
    RpcAccountFromJSONTyped,
    RpcAccountToJSON,
} from './RpcAccount';

/**
 * @type RpcCreateAccountResponseAccount
 * 
 * @export
 */
export type RpcCreateAccountResponseAccount = RpcAccount;

export function RpcCreateAccountResponseAccountFromJSON(json: any): RpcCreateAccountResponseAccount {
    return RpcCreateAccountResponseAccountFromJSONTyped(json, false);
}

export function RpcCreateAccountResponseAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateAccountResponseAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...RpcAccountFromJSONTyped(json, true) };
}

export function RpcCreateAccountResponseAccountToJSON(value?: RpcCreateAccountResponseAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfRpcAccount(value)) {
        return RpcAccountToJSON(value as RpcAccount);
    }

    return {};
}

