/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RpcSubmissionSnippet } from './RpcSubmissionSnippet';
import {
    instanceOfRpcSubmissionSnippet,
    RpcSubmissionSnippetFromJSON,
    RpcSubmissionSnippetFromJSONTyped,
    RpcSubmissionSnippetToJSON,
} from './RpcSubmissionSnippet';

/**
 * @type RpcCreateSubmissionResponseSubmissionSnippet
 * 
 * @export
 */
export type RpcCreateSubmissionResponseSubmissionSnippet = RpcSubmissionSnippet;

export function RpcCreateSubmissionResponseSubmissionSnippetFromJSON(json: any): RpcCreateSubmissionResponseSubmissionSnippet {
    return RpcCreateSubmissionResponseSubmissionSnippetFromJSONTyped(json, false);
}

export function RpcCreateSubmissionResponseSubmissionSnippetFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateSubmissionResponseSubmissionSnippet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...RpcSubmissionSnippetFromJSONTyped(json, true) };
}

export function RpcCreateSubmissionResponseSubmissionSnippetToJSON(value?: RpcCreateSubmissionResponseSubmissionSnippet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfRpcSubmissionSnippet(value)) {
        return RpcSubmissionSnippetToJSON(value as RpcSubmissionSnippet);
    }

    return {};
}

