/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcProblemExample } from './RpcProblemExample';
import {
    RpcProblemExampleFromJSON,
    RpcProblemExampleFromJSONTyped,
    RpcProblemExampleToJSON,
} from './RpcProblemExample';

/**
 * 
 * @export
 * @interface RpcCreateProblemRequest
 */
export interface RpcCreateProblemRequest {
    /**
     * 
     * @type {string}
     * @memberof RpcCreateProblemRequest
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof RpcCreateProblemRequest
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof RpcCreateProblemRequest
     */
    timeLimitInMillisecond: number;
    /**
     * 
     * @type {number}
     * @memberof RpcCreateProblemRequest
     */
    memoryLimitInByte: number;
    /**
     * 
     * @type {Array<RpcProblemExample>}
     * @memberof RpcCreateProblemRequest
     */
    exampleList: Array<RpcProblemExample>;
}

/**
 * Check if a given object implements the RpcCreateProblemRequest interface.
 */
export function instanceOfRpcCreateProblemRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "displayName" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "timeLimitInMillisecond" in value;
    isInstance = isInstance && "memoryLimitInByte" in value;
    isInstance = isInstance && "exampleList" in value;

    return isInstance;
}

export function RpcCreateProblemRequestFromJSON(json: any): RpcCreateProblemRequest {
    return RpcCreateProblemRequestFromJSONTyped(json, false);
}

export function RpcCreateProblemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateProblemRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'displayName': json['DisplayName'],
        'description': json['Description'],
        'timeLimitInMillisecond': json['TimeLimitInMillisecond'],
        'memoryLimitInByte': json['MemoryLimitInByte'],
        'exampleList': ((json['ExampleList'] as Array<any>).map(RpcProblemExampleFromJSON)),
    };
}

export function RpcCreateProblemRequestToJSON(value?: RpcCreateProblemRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DisplayName': value.displayName,
        'Description': value.description,
        'TimeLimitInMillisecond': value.timeLimitInMillisecond,
        'MemoryLimitInByte': value.memoryLimitInByte,
        'ExampleList': ((value.exampleList as Array<any>).map(RpcProblemExampleToJSON)),
    };
}

