/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcCreateAccountRequest
 */
export interface RpcCreateAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof RpcCreateAccountRequest
     */
    accountName: string;
    /**
     * 
     * @type {string}
     * @memberof RpcCreateAccountRequest
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof RpcCreateAccountRequest
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof RpcCreateAccountRequest
     */
    password: string;
}

/**
 * Check if a given object implements the RpcCreateAccountRequest interface.
 */
export function instanceOfRpcCreateAccountRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountName" in value;
    isInstance = isInstance && "displayName" in value;
    isInstance = isInstance && "role" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function RpcCreateAccountRequestFromJSON(json: any): RpcCreateAccountRequest {
    return RpcCreateAccountRequestFromJSONTyped(json, false);
}

export function RpcCreateAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateAccountRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountName': json['AccountName'],
        'displayName': json['DisplayName'],
        'role': json['Role'],
        'password': json['Password'],
    };
}

export function RpcCreateAccountRequestToJSON(value?: RpcCreateAccountRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AccountName': value.accountName,
        'DisplayName': value.displayName,
        'Role': value.role,
        'Password': value.password,
    };
}

