/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcCreateProblemResponseAuthor } from './RpcCreateProblemResponseAuthor';
import {
    RpcCreateProblemResponseAuthorFromJSON,
    RpcCreateProblemResponseAuthorFromJSONTyped,
    RpcCreateProblemResponseAuthorToJSON,
} from './RpcCreateProblemResponseAuthor';

/**
 * 
 * @export
 * @interface RpcCreateUserResponse
 */
export interface RpcCreateUserResponse {
    /**
     * 
     * @type {RpcCreateProblemResponseAuthor}
     * @memberof RpcCreateUserResponse
     */
    user: RpcCreateProblemResponseAuthor;
}

/**
 * Check if a given object implements the RpcCreateUserResponse interface.
 */
export function instanceOfRpcCreateUserResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;

    return isInstance;
}

export function RpcCreateUserResponseFromJSON(json: any): RpcCreateUserResponse {
    return RpcCreateUserResponseFromJSONTyped(json, false);
}

export function RpcCreateUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': RpcCreateProblemResponseAuthorFromJSON(json['User']),
    };
}

export function RpcCreateUserResponseToJSON(value?: RpcCreateUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'User': RpcCreateProblemResponseAuthorToJSON(value.user),
    };
}

