/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcCreateAccountResponseAccount } from './RpcCreateAccountResponseAccount';
import {
    RpcCreateAccountResponseAccountFromJSON,
    RpcCreateAccountResponseAccountFromJSONTyped,
    RpcCreateAccountResponseAccountToJSON,
} from './RpcCreateAccountResponseAccount';
import type { RpcProblemExample } from './RpcProblemExample';
import {
    RpcProblemExampleFromJSON,
    RpcProblemExampleFromJSONTyped,
    RpcProblemExampleToJSON,
} from './RpcProblemExample';

/**
 * 
 * @export
 * @interface RpcCreateProblemResponse
 */
export interface RpcCreateProblemResponse {
    /**
     * 
     * @type {number}
     * @memberof RpcCreateProblemResponse
     */
    iD: number;
    /**
     * 
     * @type {string}
     * @memberof RpcCreateProblemResponse
     */
    displayName: string;
    /**
     * 
     * @type {RpcCreateAccountResponseAccount}
     * @memberof RpcCreateProblemResponse
     */
    author: RpcCreateAccountResponseAccount;
    /**
     * 
     * @type {string}
     * @memberof RpcCreateProblemResponse
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof RpcCreateProblemResponse
     */
    timeLimitInMillisecond: number;
    /**
     * 
     * @type {number}
     * @memberof RpcCreateProblemResponse
     */
    memoryLimitInByte: number;
    /**
     * 
     * @type {Array<RpcProblemExample>}
     * @memberof RpcCreateProblemResponse
     */
    exampleList: Array<RpcProblemExample>;
    /**
     * 
     * @type {number}
     * @memberof RpcCreateProblemResponse
     */
    createdTime: number;
    /**
     * 
     * @type {number}
     * @memberof RpcCreateProblemResponse
     */
    updatedTime: number;
}

/**
 * Check if a given object implements the RpcCreateProblemResponse interface.
 */
export function instanceOfRpcCreateProblemResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "iD" in value;
    isInstance = isInstance && "displayName" in value;
    isInstance = isInstance && "author" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "timeLimitInMillisecond" in value;
    isInstance = isInstance && "memoryLimitInByte" in value;
    isInstance = isInstance && "exampleList" in value;
    isInstance = isInstance && "createdTime" in value;
    isInstance = isInstance && "updatedTime" in value;

    return isInstance;
}

export function RpcCreateProblemResponseFromJSON(json: any): RpcCreateProblemResponse {
    return RpcCreateProblemResponseFromJSONTyped(json, false);
}

export function RpcCreateProblemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateProblemResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'displayName': json['DisplayName'],
        'author': RpcCreateAccountResponseAccountFromJSON(json['Author']),
        'description': json['Description'],
        'timeLimitInMillisecond': json['TimeLimitInMillisecond'],
        'memoryLimitInByte': json['MemoryLimitInByte'],
        'exampleList': ((json['ExampleList'] as Array<any>).map(RpcProblemExampleFromJSON)),
        'createdTime': json['CreatedTime'],
        'updatedTime': json['UpdatedTime'],
    };
}

export function RpcCreateProblemResponseToJSON(value?: RpcCreateProblemResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ID': value.iD,
        'DisplayName': value.displayName,
        'Author': RpcCreateAccountResponseAccountToJSON(value.author),
        'Description': value.description,
        'TimeLimitInMillisecond': value.timeLimitInMillisecond,
        'MemoryLimitInByte': value.memoryLimitInByte,
        'ExampleList': ((value.exampleList as Array<any>).map(RpcProblemExampleToJSON)),
        'CreatedTime': value.createdTime,
        'UpdatedTime': value.updatedTime,
    };
}

