/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcDeleteSubmissionRequest
 */
export interface RpcDeleteSubmissionRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcDeleteSubmissionRequest
     */
    iD: number;
}

/**
 * Check if a given object implements the RpcDeleteSubmissionRequest interface.
 */
export function instanceOfRpcDeleteSubmissionRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "iD" in value;

    return isInstance;
}

export function RpcDeleteSubmissionRequestFromJSON(json: any): RpcDeleteSubmissionRequest {
    return RpcDeleteSubmissionRequestFromJSONTyped(json, false);
}

export function RpcDeleteSubmissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcDeleteSubmissionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iD': json['ID'],
    };
}

export function RpcDeleteSubmissionRequestToJSON(value?: RpcDeleteSubmissionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ID': value.iD,
    };
}

