/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcDeleteTestCaseRequest
 */
export interface RpcDeleteTestCaseRequest {
    /**
     * 
     * @type {string}
     * @memberof RpcDeleteTestCaseRequest
     */
    uUID: string;
}

/**
 * Check if a given object implements the RpcDeleteTestCaseRequest interface.
 */
export function instanceOfRpcDeleteTestCaseRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uUID" in value;

    return isInstance;
}

export function RpcDeleteTestCaseRequestFromJSON(json: any): RpcDeleteTestCaseRequest {
    return RpcDeleteTestCaseRequestFromJSONTyped(json, false);
}

export function RpcDeleteTestCaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcDeleteTestCaseRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uUID': json['UUID'],
    };
}

export function RpcDeleteTestCaseRequestToJSON(value?: RpcDeleteTestCaseRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'UUID': value.uUID,
    };
}

