/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcEchoResponse
 */
export interface RpcEchoResponse {
    /**
     * 
     * @type {string}
     * @memberof RpcEchoResponse
     */
    message: string;
}

/**
 * Check if a given object implements the RpcEchoResponse interface.
 */
export function instanceOfRpcEchoResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function RpcEchoResponseFromJSON(json: any): RpcEchoResponse {
    return RpcEchoResponseFromJSONTyped(json, false);
}

export function RpcEchoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcEchoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['Message'],
    };
}

export function RpcEchoResponseToJSON(value?: RpcEchoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Message': value.message,
    };
}

