/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcAccount } from './RpcAccount';
import {
    RpcAccountFromJSON,
    RpcAccountFromJSONTyped,
    RpcAccountToJSON,
} from './RpcAccount';

/**
 * 
 * @export
 * @interface RpcGetAccountListResponse
 */
export interface RpcGetAccountListResponse {
    /**
     * 
     * @type {number}
     * @memberof RpcGetAccountListResponse
     */
    totalAccountCount: number;
    /**
     * 
     * @type {Array<RpcAccount>}
     * @memberof RpcGetAccountListResponse
     */
    accountList: Array<RpcAccount>;
}

/**
 * Check if a given object implements the RpcGetAccountListResponse interface.
 */
export function instanceOfRpcGetAccountListResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "totalAccountCount" in value;
    isInstance = isInstance && "accountList" in value;

    return isInstance;
}

export function RpcGetAccountListResponseFromJSON(json: any): RpcGetAccountListResponse {
    return RpcGetAccountListResponseFromJSONTyped(json, false);
}

export function RpcGetAccountListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetAccountListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalAccountCount': json['TotalAccountCount'],
        'accountList': ((json['AccountList'] as Array<any>).map(RpcAccountFromJSON)),
    };
}

export function RpcGetAccountListResponseToJSON(value?: RpcGetAccountListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TotalAccountCount': value.totalAccountCount,
        'AccountList': ((value.accountList as Array<any>).map(RpcAccountToJSON)),
    };
}

