/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcProblem } from './RpcProblem';
import {
    RpcProblemFromJSON,
    RpcProblemFromJSONTyped,
    RpcProblemToJSON,
} from './RpcProblem';

/**
 * 
 * @export
 * @interface RpcGetUserProblemSnippetListResponse
 */
export interface RpcGetUserProblemSnippetListResponse {
    /**
     * 
     * @type {number}
     * @memberof RpcGetUserProblemSnippetListResponse
     */
    totalProblemCount: number;
    /**
     * 
     * @type {Array<RpcProblem>}
     * @memberof RpcGetUserProblemSnippetListResponse
     */
    problemSnippetList: Array<RpcProblem>;
}

/**
 * Check if a given object implements the RpcGetUserProblemSnippetListResponse interface.
 */
export function instanceOfRpcGetUserProblemSnippetListResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "totalProblemCount" in value;
    isInstance = isInstance && "problemSnippetList" in value;

    return isInstance;
}

export function RpcGetUserProblemSnippetListResponseFromJSON(json: any): RpcGetUserProblemSnippetListResponse {
    return RpcGetUserProblemSnippetListResponseFromJSONTyped(json, false);
}

export function RpcGetUserProblemSnippetListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetUserProblemSnippetListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalProblemCount': json['TotalProblemCount'],
        'problemSnippetList': ((json['ProblemSnippetList'] as Array<any>).map(RpcProblemFromJSON)),
    };
}

export function RpcGetUserProblemSnippetListResponseToJSON(value?: RpcGetUserProblemSnippetListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TotalProblemCount': value.totalProblemCount,
        'ProblemSnippetList': ((value.problemSnippetList as Array<any>).map(RpcProblemToJSON)),
    };
}

