/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetSubmissionSnippetListRequest
 */
export interface RpcGetSubmissionSnippetListRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetSubmissionSnippetListRequest
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetSubmissionSnippetListRequest
     */
    limit: number;
}

/**
 * Check if a given object implements the RpcGetSubmissionSnippetListRequest interface.
 */
export function instanceOfRpcGetSubmissionSnippetListRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "offset" in value;
    isInstance = isInstance && "limit" in value;

    return isInstance;
}

export function RpcGetSubmissionSnippetListRequestFromJSON(json: any): RpcGetSubmissionSnippetListRequest {
    return RpcGetSubmissionSnippetListRequestFromJSONTyped(json, false);
}

export function RpcGetSubmissionSnippetListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetSubmissionSnippetListRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offset': json['Offset'],
        'limit': json['Limit'],
    };
}

export function RpcGetSubmissionSnippetListRequestToJSON(value?: RpcGetSubmissionSnippetListRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Offset': value.offset,
        'Limit': value.limit,
    };
}

