/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmission } from './RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmission';
import {
    RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmissionFromJSON,
    RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmissionFromJSONTyped,
    RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmissionToJSON,
} from './RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmission';

/**
 * 
 * @export
 * @interface RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponse
 */
export interface RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponse {
    /**
     * 
     * @type {RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmission}
     * @memberof RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponse
     */
    submission: RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmission;
}

/**
 * Check if a given object implements the RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponse interface.
 */
export function instanceOfRpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "submission" in value;

    return isInstance;
}

export function RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseFromJSON(json: any): RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponse {
    return RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseFromJSONTyped(json, false);
}

export function RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'submission': RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmissionFromJSON(json['Submission']),
    };
}

export function RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseToJSON(value?: RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Submission': RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmissionToJSON(value.submission),
    };
}

