/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcGetTestCaseResponseTestCase } from './RpcGetTestCaseResponseTestCase';
import {
    RpcGetTestCaseResponseTestCaseFromJSON,
    RpcGetTestCaseResponseTestCaseFromJSONTyped,
    RpcGetTestCaseResponseTestCaseToJSON,
} from './RpcGetTestCaseResponseTestCase';

/**
 * 
 * @export
 * @interface RpcGetTestCaseResponse
 */
export interface RpcGetTestCaseResponse {
    /**
     * 
     * @type {RpcGetTestCaseResponseTestCase}
     * @memberof RpcGetTestCaseResponse
     */
    testCase: RpcGetTestCaseResponseTestCase;
}

/**
 * Check if a given object implements the RpcGetTestCaseResponse interface.
 */
export function instanceOfRpcGetTestCaseResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "testCase" in value;

    return isInstance;
}

export function RpcGetTestCaseResponseFromJSON(json: any): RpcGetTestCaseResponse {
    return RpcGetTestCaseResponseFromJSONTyped(json, false);
}

export function RpcGetTestCaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetTestCaseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'testCase': RpcGetTestCaseResponseTestCaseFromJSON(json['TestCase']),
    };
}

export function RpcGetTestCaseResponseToJSON(value?: RpcGetTestCaseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TestCase': RpcGetTestCaseResponseTestCaseToJSON(value.testCase),
    };
}

