/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcSubmissionSnippet } from './RpcSubmissionSnippet';
import {
    RpcSubmissionSnippetFromJSON,
    RpcSubmissionSnippetFromJSONTyped,
    RpcSubmissionSnippetToJSON,
} from './RpcSubmissionSnippet';

/**
 * 
 * @export
 * @interface RpcGetUserSubmissionSnippetListResponse
 */
export interface RpcGetUserSubmissionSnippetListResponse {
    /**
     * 
     * @type {number}
     * @memberof RpcGetUserSubmissionSnippetListResponse
     */
    totalSubmissionCount: number;
    /**
     * 
     * @type {Array<RpcSubmissionSnippet>}
     * @memberof RpcGetUserSubmissionSnippetListResponse
     */
    submissionSnippetList: Array<RpcSubmissionSnippet>;
}

/**
 * Check if a given object implements the RpcGetUserSubmissionSnippetListResponse interface.
 */
export function instanceOfRpcGetUserSubmissionSnippetListResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "totalSubmissionCount" in value;
    isInstance = isInstance && "submissionSnippetList" in value;

    return isInstance;
}

export function RpcGetUserSubmissionSnippetListResponseFromJSON(json: any): RpcGetUserSubmissionSnippetListResponse {
    return RpcGetUserSubmissionSnippetListResponseFromJSONTyped(json, false);
}

export function RpcGetUserSubmissionSnippetListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetUserSubmissionSnippetListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalSubmissionCount': json['TotalSubmissionCount'],
        'submissionSnippetList': ((json['SubmissionSnippetList'] as Array<any>).map(RpcSubmissionSnippetFromJSON)),
    };
}

export function RpcGetUserSubmissionSnippetListResponseToJSON(value?: RpcGetUserSubmissionSnippetListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TotalSubmissionCount': value.totalSubmissionCount,
        'SubmissionSnippetList': ((value.submissionSnippetList as Array<any>).map(RpcSubmissionSnippetToJSON)),
    };
}

