/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcLanguage } from './RpcLanguage';
import {
    RpcLanguageFromJSON,
    RpcLanguageFromJSONTyped,
    RpcLanguageToJSON,
} from './RpcLanguage';

/**
 * 
 * @export
 * @interface RpcGetServerInfoResponse
 */
export interface RpcGetServerInfoResponse {
    /**
     * 
     * @type {boolean}
     * @memberof RpcGetServerInfoResponse
     */
    isLocal: boolean;
    /**
     * 
     * @type {Array<RpcLanguage>}
     * @memberof RpcGetServerInfoResponse
     */
    supportedLanguageList: Array<RpcLanguage>;
}

/**
 * Check if a given object implements the RpcGetServerInfoResponse interface.
 */
export function instanceOfRpcGetServerInfoResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isLocal" in value;
    isInstance = isInstance && "supportedLanguageList" in value;

    return isInstance;
}

export function RpcGetServerInfoResponseFromJSON(json: any): RpcGetServerInfoResponse {
    return RpcGetServerInfoResponseFromJSONTyped(json, false);
}

export function RpcGetServerInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetServerInfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isLocal': json['IsLocal'],
        'supportedLanguageList': ((json['SupportedLanguageList'] as Array<any>).map(RpcLanguageFromJSON)),
    };
}

export function RpcGetServerInfoResponseToJSON(value?: RpcGetServerInfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'IsLocal': value.isLocal,
        'SupportedLanguageList': ((value.supportedLanguageList as Array<any>).map(RpcLanguageToJSON)),
    };
}

