/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetUserSubmissionSnippetListRequest
 */
export interface RpcGetUserSubmissionSnippetListRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetUserSubmissionSnippetListRequest
     */
    userID: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetUserSubmissionSnippetListRequest
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetUserSubmissionSnippetListRequest
     */
    limit: number;
}

/**
 * Check if a given object implements the RpcGetUserSubmissionSnippetListRequest interface.
 */
export function instanceOfRpcGetUserSubmissionSnippetListRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userID" in value;
    isInstance = isInstance && "offset" in value;
    isInstance = isInstance && "limit" in value;

    return isInstance;
}

export function RpcGetUserSubmissionSnippetListRequestFromJSON(json: any): RpcGetUserSubmissionSnippetListRequest {
    return RpcGetUserSubmissionSnippetListRequestFromJSONTyped(json, false);
}

export function RpcGetUserSubmissionSnippetListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetUserSubmissionSnippetListRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userID': json['UserID'],
        'offset': json['Offset'],
        'limit': json['Limit'],
    };
}

export function RpcGetUserSubmissionSnippetListRequestToJSON(value?: RpcGetUserSubmissionSnippetListRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'UserID': value.userID,
        'Offset': value.offset,
        'Limit': value.limit,
    };
}

