/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RpcSubmission } from './RpcSubmission';
import {
    instanceOfRpcSubmission,
    RpcSubmissionFromJSON,
    RpcSubmissionFromJSONTyped,
    RpcSubmissionToJSON,
} from './RpcSubmission';

/**
 * @type RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmission
 * 
 * @export
 */
export type RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmission = RpcSubmission;

export function RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmissionFromJSON(json: any): RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmission {
    return RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmissionFromJSONTyped(json, false);
}

export function RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmission {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...RpcSubmissionFromJSONTyped(json, true) };
}

export function RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmissionToJSON(value?: RpcGetAndUpdateFirstSubmittedSubmissionToExecutingResponseSubmission | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfRpcSubmission(value)) {
        return RpcSubmissionToJSON(value as RpcSubmission);
    }

    return {};
}

