/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcLanguage
 */
export interface RpcLanguage {
    /**
     * 
     * @type {string}
     * @memberof RpcLanguage
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof RpcLanguage
     */
    name: string;
}

/**
 * Check if a given object implements the RpcLanguage interface.
 */
export function instanceOfRpcLanguage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function RpcLanguageFromJSON(json: any): RpcLanguage {
    return RpcLanguageFromJSONTyped(json, false);
}

export function RpcLanguageFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcLanguage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['Value'],
        'name': json['Name'],
    };
}

export function RpcLanguageToJSON(value?: RpcLanguage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Value': value.value,
        'Name': value.name,
    };
}

