/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcProblemExample
 */
export interface RpcProblemExample {
    /**
     * 
     * @type {string}
     * @memberof RpcProblemExample
     */
    input: string;
    /**
     * 
     * @type {string}
     * @memberof RpcProblemExample
     */
    output: string;
}

/**
 * Check if a given object implements the RpcProblemExample interface.
 */
export function instanceOfRpcProblemExample(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "input" in value;
    isInstance = isInstance && "output" in value;

    return isInstance;
}

export function RpcProblemExampleFromJSON(json: any): RpcProblemExample {
    return RpcProblemExampleFromJSONTyped(json, false);
}

export function RpcProblemExampleFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcProblemExample {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'input': json['Input'],
        'output': json['Output'],
    };
}

export function RpcProblemExampleToJSON(value?: RpcProblemExample | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Input': value.input,
        'Output': value.output,
    };
}

