/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcSubmissionSetting
 */
export interface RpcSubmissionSetting {
    /**
     * 
     * @type {boolean}
     * @memberof RpcSubmissionSetting
     */
    disableSubmissionCreation: boolean;
}

/**
 * Check if a given object implements the RpcSubmissionSetting interface.
 */
export function instanceOfRpcSubmissionSetting(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "disableSubmissionCreation" in value;

    return isInstance;
}

export function RpcSubmissionSettingFromJSON(json: any): RpcSubmissionSetting {
    return RpcSubmissionSettingFromJSONTyped(json, false);
}

export function RpcSubmissionSettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcSubmissionSetting {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'disableSubmissionCreation': json['DisableSubmissionCreation'],
    };
}

export function RpcSubmissionSettingToJSON(value?: RpcSubmissionSetting | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DisableSubmissionCreation': value.disableSubmissionCreation,
    };
}

