/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RpcSubmissionStatus } from './RpcSubmissionStatus';
import {
    instanceOfRpcSubmissionStatus,
    RpcSubmissionStatusFromJSON,
    RpcSubmissionStatusFromJSONTyped,
    RpcSubmissionStatusToJSON,
} from './RpcSubmissionStatus';

/**
 * @type RpcSubmissionStatus
 * 
 * @export
 */
export type RpcSubmissionStatus = RpcSubmissionStatus;

export function RpcSubmissionStatusFromJSON(json: any): RpcSubmissionStatus {
    return RpcSubmissionStatusFromJSONTyped(json, false);
}

export function RpcSubmissionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcSubmissionStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...RpcSubmissionStatusFromJSONTyped(json, true) };
}

export function RpcSubmissionStatusToJSON(value?: RpcSubmissionStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfRpcSubmissionStatus(value)) {
        return RpcSubmissionStatusToJSON(value as RpcSubmissionStatus);
    }

    return {};
}

