/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcSubmissionProblemSnippet
 */
export interface RpcSubmissionProblemSnippet {
    /**
     * 
     * @type {string}
     * @memberof RpcSubmissionProblemSnippet
     */
    uUID: string;
    /**
     * 
     * @type {string}
     * @memberof RpcSubmissionProblemSnippet
     */
    displayName: string;
}

/**
 * Check if a given object implements the RpcSubmissionProblemSnippet interface.
 */
export function instanceOfRpcSubmissionProblemSnippet(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uUID" in value;
    isInstance = isInstance && "displayName" in value;

    return isInstance;
}

export function RpcSubmissionProblemSnippetFromJSON(json: any): RpcSubmissionProblemSnippet {
    return RpcSubmissionProblemSnippetFromJSONTyped(json, false);
}

export function RpcSubmissionProblemSnippetFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcSubmissionProblemSnippet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uUID': json['UUID'],
        'displayName': json['DisplayName'],
    };
}

export function RpcSubmissionProblemSnippetToJSON(value?: RpcSubmissionProblemSnippet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'UUID': value.uUID,
        'DisplayName': value.displayName,
    };
}

