/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RpcSubmissionResult } from './RpcSubmissionResult';
import {
    instanceOfRpcSubmissionResult,
    RpcSubmissionResultFromJSON,
    RpcSubmissionResultFromJSONTyped,
    RpcSubmissionResultToJSON,
} from './RpcSubmissionResult';

/**
 * @type RpcSubmissionResult
 * 
 * @export
 */
export type RpcSubmissionResult = RpcSubmissionResult;

export function RpcSubmissionResultFromJSON(json: any): RpcSubmissionResult {
    return RpcSubmissionResultFromJSONTyped(json, false);
}

export function RpcSubmissionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcSubmissionResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...RpcSubmissionResultFromJSONTyped(json, true) };
}

export function RpcSubmissionResultToJSON(value?: RpcSubmissionResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfRpcSubmissionResult(value)) {
        return RpcSubmissionResultToJSON(value as RpcSubmissionResult);
    }

    return {};
}

