/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RpcSubmissionSetting } from './RpcSubmissionSetting';
import {
    instanceOfRpcSubmissionSetting,
    RpcSubmissionSettingFromJSON,
    RpcSubmissionSettingFromJSONTyped,
    RpcSubmissionSettingToJSON,
} from './RpcSubmissionSetting';

/**
 * @type RpcSettingSubmission
 * 
 * @export
 */
export type RpcSettingSubmission = RpcSubmissionSetting;

export function RpcSettingSubmissionFromJSON(json: any): RpcSettingSubmission {
    return RpcSettingSubmissionFromJSONTyped(json, false);
}

export function RpcSettingSubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcSettingSubmission {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...RpcSubmissionSettingFromJSONTyped(json, true) };
}

export function RpcSettingSubmissionToJSON(value?: RpcSettingSubmission | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfRpcSubmissionSetting(value)) {
        return RpcSubmissionSettingToJSON(value as RpcSubmissionSetting);
    }

    return {};
}

