/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcUpdateTestCaseRequest
 */
export interface RpcUpdateTestCaseRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcUpdateTestCaseRequest
     */
    iD: number;
    /**
     * 
     * @type {string}
     * @memberof RpcUpdateTestCaseRequest
     */
    input: string;
    /**
     * 
     * @type {string}
     * @memberof RpcUpdateTestCaseRequest
     */
    output: string;
    /**
     * 
     * @type {boolean}
     * @memberof RpcUpdateTestCaseRequest
     */
    isHidden: boolean;
}

/**
 * Check if a given object implements the RpcUpdateTestCaseRequest interface.
 */
export function instanceOfRpcUpdateTestCaseRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "iD" in value;
    isInstance = isInstance && "input" in value;
    isInstance = isInstance && "output" in value;
    isInstance = isInstance && "isHidden" in value;

    return isInstance;
}

export function RpcUpdateTestCaseRequestFromJSON(json: any): RpcUpdateTestCaseRequest {
    return RpcUpdateTestCaseRequestFromJSONTyped(json, false);
}

export function RpcUpdateTestCaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcUpdateTestCaseRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'input': json['Input'],
        'output': json['Output'],
        'isHidden': json['IsHidden'],
    };
}

export function RpcUpdateTestCaseRequestToJSON(value?: RpcUpdateTestCaseRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ID': value.iD,
        'Input': value.input,
        'Output': value.output,
        'IsHidden': value.isHidden,
    };
}

