/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcGetServerInfoResponseSetting } from './RpcGetServerInfoResponseSetting';
import {
    RpcGetServerInfoResponseSettingFromJSON,
    RpcGetServerInfoResponseSettingFromJSONTyped,
    RpcGetServerInfoResponseSettingToJSON,
} from './RpcGetServerInfoResponseSetting';

/**
 * 
 * @export
 * @interface RpcUpdateSettingResponse
 */
export interface RpcUpdateSettingResponse {
    /**
     * 
     * @type {RpcGetServerInfoResponseSetting}
     * @memberof RpcUpdateSettingResponse
     */
    setting: RpcGetServerInfoResponseSetting;
}

/**
 * Check if a given object implements the RpcUpdateSettingResponse interface.
 */
export function instanceOfRpcUpdateSettingResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "setting" in value;

    return isInstance;
}

export function RpcUpdateSettingResponseFromJSON(json: any): RpcUpdateSettingResponse {
    return RpcUpdateSettingResponseFromJSONTyped(json, false);
}

export function RpcUpdateSettingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcUpdateSettingResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'setting': RpcGetServerInfoResponseSettingFromJSON(json['Setting']),
    };
}

export function RpcUpdateSettingResponseToJSON(value?: RpcUpdateSettingResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Setting': RpcGetServerInfoResponseSettingToJSON(value.setting),
    };
}

