/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcCreateTestCaseResponseTestCaseSnippet } from './RpcCreateTestCaseResponseTestCaseSnippet';
import {
    RpcCreateTestCaseResponseTestCaseSnippetFromJSON,
    RpcCreateTestCaseResponseTestCaseSnippetFromJSONTyped,
    RpcCreateTestCaseResponseTestCaseSnippetToJSON,
} from './RpcCreateTestCaseResponseTestCaseSnippet';

/**
 * 
 * @export
 * @interface RpcUpdateTestCaseResponse
 */
export interface RpcUpdateTestCaseResponse {
    /**
     * 
     * @type {RpcCreateTestCaseResponseTestCaseSnippet}
     * @memberof RpcUpdateTestCaseResponse
     */
    testCaseSnippet: RpcCreateTestCaseResponseTestCaseSnippet;
}

/**
 * Check if a given object implements the RpcUpdateTestCaseResponse interface.
 */
export function instanceOfRpcUpdateTestCaseResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "testCaseSnippet" in value;

    return isInstance;
}

export function RpcUpdateTestCaseResponseFromJSON(json: any): RpcUpdateTestCaseResponse {
    return RpcUpdateTestCaseResponseFromJSONTyped(json, false);
}

export function RpcUpdateTestCaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcUpdateTestCaseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'testCaseSnippet': RpcCreateTestCaseResponseTestCaseSnippetFromJSON(json['TestCaseSnippet']),
    };
}

export function RpcUpdateTestCaseResponseToJSON(value?: RpcUpdateTestCaseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TestCaseSnippet': RpcCreateTestCaseResponseTestCaseSnippetToJSON(value.testCaseSnippet),
    };
}

