/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.4.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcGetServerInfoResponseSetting } from './RpcGetServerInfoResponseSetting';
import {
    RpcGetServerInfoResponseSettingFromJSON,
    RpcGetServerInfoResponseSettingFromJSONTyped,
    RpcGetServerInfoResponseSettingToJSON,
} from './RpcGetServerInfoResponseSetting';

/**
 * 
 * @export
 * @interface RpcUpdateSettingRequest
 */
export interface RpcUpdateSettingRequest {
    /**
     * 
     * @type {RpcGetServerInfoResponseSetting}
     * @memberof RpcUpdateSettingRequest
     */
    setting: RpcGetServerInfoResponseSetting;
}

/**
 * Check if a given object implements the RpcUpdateSettingRequest interface.
 */
export function instanceOfRpcUpdateSettingRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "setting" in value;

    return isInstance;
}

export function RpcUpdateSettingRequestFromJSON(json: any): RpcUpdateSettingRequest {
    return RpcUpdateSettingRequestFromJSONTyped(json, false);
}

export function RpcUpdateSettingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcUpdateSettingRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'setting': RpcGetServerInfoResponseSettingFromJSON(json['Setting']),
    };
}

export function RpcUpdateSettingRequestToJSON(value?: RpcUpdateSettingRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Setting': RpcGetServerInfoResponseSettingToJSON(value.setting),
    };
}

