// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/google/wire"

	"github.com/tranHieuDev23/cato/internal/app"
	"github.com/tranHieuDev23/cato/internal/configs"
	"github.com/tranHieuDev23/cato/internal/dataaccess"
	"github.com/tranHieuDev23/cato/internal/dataaccess/db"
	"github.com/tranHieuDev23/cato/internal/handlers"
	"github.com/tranHieuDev23/cato/internal/handlers/http"
	"github.com/tranHieuDev23/cato/internal/handlers/http/middlewares"
	"github.com/tranHieuDev23/cato/internal/logic"
	"github.com/tranHieuDev23/cato/internal/utils"
)

// Injectors from wire.go:

func InitializeCato(filePath configs.ConfigFilePath) (app.Cato, func(), error) {
	config, err := configs.NewConfig(filePath)
	if err != nil {
		return nil, nil, err
	}
	database := config.Database
	gormDB, err := db.InitializeDB(database)
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup, err := utils.InitializeLogger()
	if err != nil {
		return nil, nil, err
	}
	migrator := db.NewMigrator(gormDB, logger)
	auth := config.Auth
	hash := auth.Hash
	logicHash := logic.NewHash(hash, logger)
	accountDataAccessor := db.NewAccountDataAccessor(gormDB, logger)
	token := auth.Token
	logicToken, err := logic.NewToken(accountDataAccessor, token, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	role := logic.NewRole(logger)
	accountPasswordDataAccessor := db.NewAccountPasswordDataAccessor(gormDB, logger)
	account := logic.NewAccount(logicHash, logicToken, role, accountDataAccessor, accountPasswordDataAccessor, gormDB, logger)
	problemDataAccessor := db.NewProblemDataAccessor(gormDB, logger)
	problemExampleDataAccessor := db.NewProblemExampleDataAccessor(gormDB, logger)
	problem := logic.NewProblem(logicToken, role, accountDataAccessor, problemDataAccessor, problemExampleDataAccessor, logger, gormDB)
	testCaseDataAccessor := db.NewTestCaseDataAccessor(gormDB, logger)
	testCase := logic.NewTestCase(logicToken, role, problemDataAccessor, testCaseDataAccessor, gormDB, logger)
	apiServer := http.NewAPIServerHandler(account, problem, testCase, logger)
	v := middlewares.InitializePJRPCMiddlewareList()
	httpAuth, err := middlewares.NewHTTPAuth(logicToken, token, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	v2 := middlewares.InitalizeHTTPMiddlewareList(httpAuth)
	spaHandler := http.NewSPAHandler()
	configsHTTP := config.HTTP
	server := http.NewServer(apiServer, v, v2, spaHandler, logger, configsHTTP)
	cato := app.NewCato(migrator, server, logger)
	return cato, func() {
		cleanup()
	}, nil
}

// wire.go:

var WireSet = wire.NewSet(utils.WireSet, configs.WireSet, dataaccess.WireSet, logic.WireSet, handlers.WireSet, app.WireSet)
